/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppNavDrawer: typeof import('./components/common/AppNavDrawer.vue')['default']
    AppToast: typeof import('./components/common/AppToast.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OssDetailDialog: typeof import('./components/oss/OssDetailDialog.vue')['default']
    OssFilterBar: typeof import('./components/oss/OssFilterBar.vue')['default']
    OssTable: typeof import('./components/oss/OssTable.vue')['default']
    ProjectDetailDialog: typeof import('./components/project/ProjectDetailDialog.vue')['default']
    ProjectFilterBar: typeof import('./components/project/ProjectFilterBar.vue')['default']
    ProjectTable: typeof import('./components/project/ProjectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScopePolicyForm: typeof import('./components/settings/ScopePolicyForm.vue')['default']
    TagManager: typeof import('./components/settings/TagManager.vue')['default']
  }
}
